reference_frame: "gps_origin"

control_action_interval: 0.01 # [s]
uvdar_msg_interval: 0.1 # [s]

# offset from the leader position to be maintained
desired_offset:
  x: -4.0 # [m]
  y: 5.0 # [m]
  z: 0.0 # [m]

# rotation offset around the world vertical axis
heading_offset: 0.3 # [rad]

# Noise parameters of the Kalman velocity estimator

# Process noise
Q: [10, 0, 0, 0, 0, 0,
    0, 10, 0, 0, 0, 0,
    0, 0, 10, 0, 0, 0,
    0, 0, 0, 5, 0, 0,
    0, 0, 0, 0, 5, 0,
    0, 0, 0, 0, 0, 5]

# # Measurement noise
R: [50, 0, 0,
    0, 50, 0,
    0, 0, 50]

use_estimator: true
# use_trajectory_reference: true
# use_speed_tracker: true

los_ideal: 4.5
# # For speed tracker only
los_min: 4
los_max: 12